[package]
name = "smithril-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
smithril = { path = "../." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ipc-channel = "0.18.1"
