[package]
name = "smithril-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
smithril-lib = { path = "../smithril-lib" }
tokio = { version = "1", features = ["full"] }
once_cell = "1.19.0"
duration-string = "0.4.0"

[lib]
crate-type =["staticlib"]

[build-dependencies]
cbindgen = "0.27.0"
