name: Format, build and lint test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: Install Packages (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev ninja-build

    - name: Setup Python Environment
      run: |
        python3 -m venv ~/.venv
        source ~/.venv/bin/activate
        python3 -m pip install meson
        echo "$HOME/.venv/bin/" >> $GITHUB_PATH

    - uses: actions/checkout@v4

    - name: Cache Sys Solvers
      id: cache-sys-solvers
      uses: actions/cache@v4
      with:
        path: ~/.smithril
        key: ${{ runner.os }}-sys-solvers

    - name: Setup default rustc
      run: rustup default stable

    - name: Format
      run: cargo fmt --check --all

    - name: Build
      run: cargo build --verbose --workspace

    - name: Lint
      run: cargo clippy --all-targets --all-features --workspace

    - name: Run tests
      run: cargo test --verbose --workspace

    - name: Setup nightly rustc
      run: rustup default nightly


    - name: Install cargo-c
      run: cargo test --verbose --workspace

    - name: Run cbuild
      run: cargo cbuild --destdir="/tmp/smithril"
